export const blogList = [
    { id: 1, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog1.png',std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png'  },
    { id: 2, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog2.png',std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png'  },
    { id: 3, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog3.png',std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png'  },
    { id: 4, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog4.png' , std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 5, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog5.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 6, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog6.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 7, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog7.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 8, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog8.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 9, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog9.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 10, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog5.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 11, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog1.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 12, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog3.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 13, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog8.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 14, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog6.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 15, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog2.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 16, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog3.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 17, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog4.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
    { id: 18, by:"Best LearnPress WordPress Theme Collection for 2023", title: "Looking for an amazing & well-functional LearnPress WordPress Theme? Online education...", levels:"all levels", lessons:"20", weeks:"2Weeks", students:"156 students", price:"$52", offer:"free", des:"view more", image: '/images/home/blog9.png' ,std:'/images/home/img/std.png',week:'/images/home/img/week.png',levelIcon:'/images/home/img/levels.png',lessonsIcon:'/images/home/img/lessons.png',quiz:'/images/home/img/quiz.png' },
];



export const blogCategory = [
    {id:1, name:"Commercial", number:"15"},
    {id:1, name:"Office", number:"15"},
    {id:1, name:"Shop", number:"15"},
    {id:1, name:"Educate", number:"15"},
    {id:1, name:"Academy", number:"15"},
    {id:1, name:"Single family home", number:"15"},

]